### ISSUE TITLE
"runtime error: invalid memory address"

### ISSUE THREAD

**Issue by SuperPHIJKLMNOP** [subfinder/subfinder#114]
I'm getting this error when running "./subfinder -d tesla.services". I'm using subfinder 1.1.1 on macOS High Sierra. I only get this error with this domain

```
Found Wildcard DNS at tesla.services
 - 72.52.10.14
Running enumeration on tesla.services
2018/07/09 20:22:00 panic while running job: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x12c06e0]

goroutine 70 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc420168460)
	/Users/clem/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x1317420, 0x15328f0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/sslcertificates.Query(0xc42016e560, 0x2, 0x2, 0x12a8e01, 0x1540101)
	/Users/clem/go/src/github.com/subfinder/subfinder/libsubfinder/sources/sslcertificates/sslcertificates.go:35 +0xf0
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc4201b4000, 0xc420168460)
	/Users/clem/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc4201b4000, 0xf)
	/Users/clem/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/Users/clem/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f
```

**Comment by picatz** [comment]
@SuperPHIJKLMNOP 👋 Hello and thanks for submitting the issue!

This is actually a [**known issue**](https://github.com/subfinder/subfinder/issues/103) that has been [fixed](https://github.com/subfinder/subfinder/issues/106) in version `1.1.3`. We recommend you upgrade your installation with the following:

```
$ go get -u github.com/subfinder/subfinder
```

> **Note**: If you see the issue persist after upgrading, please let us know 🙏
