### ISSUE TITLE
panic while 

### ISSUE THREAD

**Issue by whoot** [subfinder/subfinder#138]
Subfinder crashes when using a domain with a second tld.

Example: 

```
subfinder -d redacted.com.br -v --sources all

[...]
Running Source: ThreatMiner
Running Source: WaybackArchive
Running enumeration on redacted.com.br
2018/08/20 16:48:44 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 25 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc420078780)
	/root/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x716ea0, 0x93aa30)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4200ea900, 0x2, 0x2, 0x68cc01, 0x101)
	/root/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x70e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc42009ad20, 0xc420078780)
	/root/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc42009ad20, 0x6)
	/root/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/root/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f
```

**go version**
go version go1.10.3 linux/amd64

**OS**
Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux

**Comment by Mzack9999** [comment]
Thanks @whoot for reporting this.

Probably the issue is related to an outdated version of subfinder. Please ensure you are running the latest version, we recently released a fix. If you are using go get the official way to update is the following:

```
go get -u github.com/subfinder/subfinder
```
