### ISSUE TITLE
Panic when running a job

### ISSUE THREAD

**Issue by random-robbie** [subfinder/subfinder#139]
Request
---

```
/home/host/find/subfinder/subfinder -d americansystems.com -v -o /home/host/find/data/americansystems.com.txt2
```

Response
---
```
Running enumeration on americansystems.com
2018/08/21 09:54:13 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 78 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc4201b4460)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x718040, 0x93ba30)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4201a65a0, 0x2, 0x2, 0x68cc01, 0x101)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x70e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc4200aebe0, 0xc4201b4460)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc4200aebe0, 0xb)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f

```

Go Version
---
```
go version go1.13 linux/amd64
```

Subfinder Version
---
```
===============================================
-=Subfinder v1.1.3 github.com/subfinder/subfinder
===============================================
```

OS
---

```
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-32-generic x86_64)
```

I've rebuilt subfinder a few times and still the same issue i am not sure why it's doing it.

**Comment by random-robbie** [comment]
Same issue sorry.

```
Running enumeration on google.com
2018/08/21 10:26:00 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 27 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc420200280)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x716da0, 0x93aa30)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4201a6120, 0x2, 0x2, 0x68c001, 0x940101)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x70e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc4201e4000, 0xc420200280)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc4201e4000, 0x7)
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
        /home/host/GO/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f


```

**Comment by Ice3man543** [comment]
@random-robbie Please see [this](https://github.com/subfinder/subfinder/issues/137#issuecomment-414273473)

**Comment by codingo** [comment]
Closing this as /research/ addresses it and will soon be a part of the active master.
